import { StyleSheet } from "react-native";

export const PostCreateStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#071A1B",
  },
  flex: {
    flex: 1,
  },
  container: {
    flex: 1,
    paddingHorizontal: 16,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 14,
    marginBottom: 12,
  },
  closeBtn: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
    justifyContent: "center",
    alignItems: "center",
  },
  closeBtnPressed: {
    backgroundColor: "rgba(255, 255, 255, 0.12)",
    transform: [{ scale: 0.96 }],
  },
  headerTitleContainer: {
    flex: 1,
    alignItems: "center",
  },
  headerTitle: {
    fontSize: 17,
    fontWeight: "800",
    color: "#F8FAFC",
  },
  publishBtn: {
    backgroundColor: "#A3E635",
    paddingHorizontal: 16,
    paddingVertical: 9,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#A3E635",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 3,
  },
  publishBtnPressed: {
    opacity: 0.85,
    transform: [{ scale: 0.97 }],
  },
  publishBtnContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  publishBtnText: {
    fontSize: 13,
    fontWeight: "800",
    color: "#071A1B",
  },
  publishBtnTextDisabled: {
    color: "#64748B",
  },
  btnDisabled: {
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    borderColor: "rgba(255, 255, 255, 0.08)",
    borderWidth: 1,
    shadowOpacity: 0,
    elevation: 0,
  },
  card: {
    backgroundColor: "rgba(20, 38, 38, 0.75)",
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
    gap: 12,
    flex: 1,
    marginBottom: 16,
  },
  bannerError: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "rgba(248, 113, 113, 0.1)",
    borderWidth: 1,
    borderColor: "rgba(248, 113, 113, 0.2)",
    padding: 12,
    borderRadius: 12,
  },
  bannerErrorText: {
    color: "#F87171",
    fontSize: 13,
    fontWeight: "600",
  },
  titleInputContainer: {
    backgroundColor: "#0B1516",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
  },
  contentInputContainer: {
    flex: 1,
    backgroundColor: "#0B1516",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
    padding: 12,
  },
  inputFocused: {
    borderColor: "#A3E635",
    borderWidth: 1.5,
  },
  titleInput: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    fontWeight: "700",
    color: "#F8FAFC",
  },
  contentInput: {
    flex: 1,
    fontSize: 14,
    color: "#E2E8F0",
    lineHeight: 22,
    textAlignVertical: "top",
  },
  cardFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: 8,
  },
  hintBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "rgba(163, 230, 53, 0.1)",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(163, 230, 53, 0.2)",
  },
  hintBadgeText: {
    fontSize: 12,
    color: "#A3E635",
    fontWeight: "700",
  },
  charCountBadge: {
    backgroundColor: "rgba(255, 255, 255, 0.04)",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 10,
  },
  charCountBadgeWarning: {
    backgroundColor: "rgba(248, 113, 113, 0.15)",
  },
  charCountText: {
    fontSize: 12,
    color: "#64748B",
    fontWeight: "600",
  },
  charCountLimit: {
    color: "#F87171",
    fontWeight: "700",
  },
  generateBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "rgba(163, 230, 53, 0.12)",
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(163, 230, 53, 0.3)",
  },
  generateBtnPressed: {
    backgroundColor: "rgba(163, 230, 53, 0.25)",
    transform: [{ scale: 0.96 }],
  },
  generateBtnText: {
    fontSize: 12,
    color: "#A3E635",
    fontWeight: "700",
  },
});
