 import { StyleSheet } from "react-native";
 export const PostCardStyles = StyleSheet.create({
  card: {
    backgroundColor: "rgba(20, 38, 38, 0.75)", // Glassmorphic dark-teal card
    borderRadius: 20,
    padding: 18,
    marginHorizontal: 16,
    marginVertical: 8,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
    shadowColor: "#000",
    shadowOpacity: 0.25,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  cardHighlighted: {
    borderColor: "#A3E635",
    borderWidth: 1.5,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 14,
    backgroundColor: "rgba(163, 230, 53, 0.15)",
    borderWidth: 1,
    borderColor: "rgba(163, 230, 53, 0.3)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  avatarText: {
    color: "#A3E635",
    fontWeight: "800",
    fontSize: 16,
  },
  headerInfo: {
    flex: 1,
  },
  username: {
    fontWeight: "700",
    fontSize: 15,
    color: "#F8FAFC",
  },
  timestamp: {
    fontSize: 12,
    color: "#64748B",
    marginTop: 2,
  },
  body: {
    fontSize: 15,
    color: "#E2E8F0",
    lineHeight: 22,
    marginBottom: 16,
  },
  actions: {
    flexDirection: "row",
    gap: 12,
  },
  actionButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "rgba(255, 255, 255, 0.04)",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.05)",
  },
  actionButtonActive: {
    backgroundColor: "rgba(163, 230, 53, 0.12)",
    borderColor: "rgba(163, 230, 53, 0.25)",
  },
  actionText: {
    fontSize: 13,
    color: "#94A3B8",
    fontWeight: "600",
  },
  actionTextActive: {
    color: "#A3E635",
  },
  commentsSection: {
    marginTop: 14,
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: "rgba(255, 255, 255, 0.08)",
  },
  noCommentsText: {
    color: "#64748B",
    fontSize: 13,
    marginBottom: 10,
    fontStyle: "italic",
  },
  commentRow: {
    flexDirection: "row",
    gap: 6,
    marginBottom: 8,
    backgroundColor: "rgba(0, 0, 0, 0.2)",
    padding: 10,
    borderRadius: 10,
  },
  commentAuthor: {
    fontWeight: "700",
    fontSize: 13,
    color: "#A3E635",
  },
  commentText: {
    fontSize: 13,
    color: "#E2E8F0",
    flexShrink: 1,
  },
  commentInputRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 8,
  },
  commentInput: {
    flex: 1,
    backgroundColor: "#0B1516",
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 13,
    color: "#F8FAFC",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
  },
  sendBtn: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: "#A3E635",
    justifyContent: "center",
    alignItems: "center",
  },
  sendBtnDisabled: {
    opacity: 0.4,
  },
});